//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaOSMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AndamentoOS
    {
        public AndamentoOS()
        {
            this.OrdemServico = new HashSet<OrdemServico>();
        }
    
        public int IdAndamentoOS { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<OrdemServico> OrdemServico { get; set; }
    }
}
