//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaOSMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        public Cargo()
        {
            this.Funcionario = new HashSet<Funcionario>();
        }
    
        public int IdCargo { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Funcionario> Funcionario { get; set; }
    }
}
