//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaOSMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.OrdemServico = new HashSet<OrdemServico>();
            this.Telefone = new HashSet<Telefone>();
        }
    
        public int IdCliente { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string Logradouro { get; set; }
        public string Numero { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string CEP { get; set; }
        public string Email { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public string Sexo { get; set; }
    
        public virtual ICollection<OrdemServico> OrdemServico { get; set; }
        public virtual ICollection<Telefone> Telefone { get; set; }
    }
}
