
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SistemaOSMVC.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class Equipamento
{

    public Equipamento()
    {

        this.OrdemServico = new HashSet<OrdemServico>();

    }


    public int IdEquipamento { get; set; }

    [Required(ErrorMessage = "Campo obrigatório")]
    [Display(Name = "Fabricante")]
    public int IdFabricanteFK { get; set; }

    [Required(ErrorMessage = "Campo obrigatório")]
    [Display(Name = "Tipo de Equipamento")]
    public int IdTipoEquipamento { get; set; }

    [Display(Name = "Acessorios")]
    [StringLength(50, ErrorMessage = "No máximo 50 caracteres")]
    public string Acessorios { get; set; }

    [Required(ErrorMessage = "Campo obrigatório")]
    [Display(Name = "Modelo")]
    [StringLength(150, ErrorMessage = "No máximo 150 caracteres")]
    public string Modelo { get; set; }



    public virtual Fabricante Fabricante { get; set; }

    public virtual TipoEquipamento TipoEquipamento { get; set; }

    public virtual ICollection<OrdemServico> OrdemServico { get; set; }

}

}
