//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaOSMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipamento
    {
        public Equipamento()
        {
            this.OrdemServico = new HashSet<OrdemServico>();
        }
    
        public int IdEquipamento { get; set; }
        public int IdFabricanteFK { get; set; }
        public int IdTipoEquipamento { get; set; }
        public string Acessorios { get; set; }
        public string Modelo { get; set; }
    
        public virtual Fabricante Fabricante { get; set; }
        public virtual TipoEquipamento TipoEquipamento { get; set; }
        public virtual ICollection<OrdemServico> OrdemServico { get; set; }
    }
}
