
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SistemaOSMVC.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class Fabricante
{

    public Fabricante()
    {

        this.Equipamento = new HashSet<Equipamento>();

    }


    public int IdFabricante { get; set; }

    [Required(ErrorMessage = "Campo obrigatório")]
    [Display(Name = "Fabricante")]
    [StringLength(50, ErrorMessage = "No máximo 50 caracteres")]
    public string Nome { get; set; }



    public virtual ICollection<Equipamento> Equipamento { get; set; }

}

}
