
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SistemaOSMVC.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class Funcionario
{

    public Funcionario()
    {

        this.OrdemServico = new HashSet<OrdemServico>();

    }


    public int IdFuncionario { get; set; }

    [Required(ErrorMessage = "Campo obrigatório")]
    [Display(Name = "Cargo")]
    public int IdCargoFK { get; set; }

    [Required(ErrorMessage = "Campo obrigatório")]
    [Display(Name = "Nome")]
    [StringLength(150, ErrorMessage = "No máximo 150 caracteres")]
    public string Nome { get; set; }

    [Required(ErrorMessage = "Campo obrigatório")]
    [Display(Name = "CPF")]
    [StringLength(14, ErrorMessage = "No máximo 14 caracteres")]
    public string CPF { get; set; }

    [Required(ErrorMessage = "Campo obrigatório")]
    [Display(Name = "Data de Nascimento")]
    public System.DateTime DataNascimento { get; set; }

    [Required(ErrorMessage = "Campo obrigatório")]
    [Display(Name = "Senha")]
    [StringLength(8, ErrorMessage = "No máximo 8 caracteres")]
    public string Senha { get; set; }

    [Required(ErrorMessage = "Campo obrigatório")]
    [Display(Name = "Login")]
    [StringLength(20, ErrorMessage = "No máximo 20 caracteres")]
    public string Login { get; set; }



    public virtual Cargo Cargo { get; set; }

    public virtual ICollection<OrdemServico> OrdemServico { get; set; }

}

}
