//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaOSMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public Funcionario()
        {
            this.OrdemServico = new HashSet<OrdemServico>();
        }
    
        public int IdFuncionario { get; set; }
        public int IdCargoFK { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public string Senha { get; set; }
        public string Login { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual ICollection<OrdemServico> OrdemServico { get; set; }
    }
}
