
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SistemaOSMVC.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class OrdemServico
{

    public OrdemServico()
    {

        this.Servico = new HashSet<Servico>();

    }


    public int IdOrdemServico { get; set; }

    [Required(ErrorMessage = "Campo obrigatório")]
    [Display(Name = "Cliente")]
    public int IdClienteFK { get; set; }

    [Required(ErrorMessage = "Campo obrigatório")]
    [Display(Name = "Funcionário Responsável")]
    public int IdFuncionarioFK { get; set; }

    [Required(ErrorMessage = "Campo obrigatório")]
    [Display(Name = "Andamento")]
    public int IdAndamentoOSFK { get; set; }

    [Required(ErrorMessage = "Campo obrigatório")]
    [Display(Name = "Equipamento")]
    public int IdEquipamentoFK { get; set; }
    
    [Required(ErrorMessage = "Campo obrigatório")]
    [Display(Name = "Defeito")]
    public int IdDefeitoFK { get; set; }

    [Display(Name = "Observação")]
    [StringLength(200, ErrorMessage = "No máximo 200 caracteres")]
    public string OBSERVACAO { get; set; }



    public virtual AndamentoOS AndamentoOS { get; set; }

    public virtual Cliente Cliente { get; set; }

    public virtual Defeito Defeito { get; set; }

    public virtual Equipamento Equipamento { get; set; }

    public virtual Funcionario Funcionario { get; set; }

    public virtual ICollection<Servico> Servico { get; set; }

}

}
