
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SistemaOSMVC.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class Telefone
{

    public int IdTelefone { get; set; }

    [Required(ErrorMessage = "Campo obrigatório")]
    [Display(Name = "Cliente")]
    public int IdClienteFK { get; set; }

    [Required(ErrorMessage = "Campo obrigatório")]
    [Display(Name = "Tipo de Telefone")]
    public int IdTipoTelefoneFK { get; set; }

    [Required(ErrorMessage = "Campo obrigatório")]
    [Display(Name = "Modelo")]
    [StringLength(14, ErrorMessage = "No máximo 14 caracteres")]
    public string Numero { get; set; }



    public virtual Cliente Cliente { get; set; }

    public virtual TipoTelefone TipoTelefone { get; set; }

}

}
