//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaOSMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TipoServico
    {
        public TipoServico()
        {
            this.Servico = new HashSet<Servico>();
        }
    
        public int IdTipoServico { get; set; }
        [Required(ErrorMessage = "Campo obrigatório")]
        [Display(Name = "Nome do Serviço")]
        [StringLength(50, ErrorMessage = "No máximo 50 caracteres")]
        public string Nome { get; set; }
    
        public virtual ICollection<Servico> Servico { get; set; }
    }
}
